### PR TITLE
newfeature: supporting to config the number of row items in a page

### PR DESCRIPTION
**Pull request by turbin**
to add an new property, named maxRowItems to config the number of items in a page.

### CODE REVIEW

**Comment by fralx** [comment]
Hi, I have checked the changes and found that getDataRenderMode returns ForcedStartPage every time when isFirstTime is false :).

**Comment by turbin** [comment]
> Hi, I have checked the changes and found that getDataRenderMode returns ForcedStartPage every time when isFirstTime is false :).

Thanks, I wolud check it later. 
would u mind to provide me some details to duplicate this issue? many thanks.

**Comment by fralx** [comment]
It seems you delete something important ``` currentRowIndex = ++currentRowIndex % maxNumRowPerPages; ```  :)

**Comment by turbin** [comment]
sorry, this patch was not testing, please retreat it. I would commit a new patch after fully testing. sorry for it again.

**Comment by turbin** [comment]
it was working, now.

**Comment by fralx** [comment]
Hi! 
In expression ```currentRowIndex = ++currentRowIndex % maxNumRowPerPages;``` if maxRowIndex will equal to zero it will be division by zero :)

**Review by fralx — CHANGES_REQUESTED** [review]
Please add check if maxNumRowPerPages equal to zero to prevent division by zero in ```currentRowIndex = ++currentRowIndex % maxNumRowPerPages;```

**Pull request closed without merging**
