### PR TITLE
improved borders

### PR DESCRIPTION
**Pull request by yanis60**
Hi,
I have done the following changes for borders:

- Added border Style.
- Removed border for shapes (idea from word, excel, fast report).
image

Check it and tell me if you like the changes ;)

### CODE REVIEW

**Comment by fralx** [comment]
Hi. Thanks for your contribution. But, what  will I do in case if I want a line with 1 pixel width :) ?

**Comment by yanis60** [comment]
borderLine = 1 is too thin and not rendered correctly (may be a bug from Qt) but if we set borderLine=2, the border line is exactly the same as borderLine= 1 on other report editor like fast report or on Excel and word.

**Comment by yanis60** [comment]
I have updated border line size, now if we set border line size to 0 the borders will be hidden.
And i added a function that returns number of rows of a data source from script.

**Comment by Jihadist** [comment]
@yanis60 please make commits more informative. If commit message contains only date no one can understand what commit really contains. You can briefly describe changes in commit message

**Comment by yanis60** [comment]
I have added shadow property for baseitem

**Comment by yanis60** [comment]
I guess you declined it :(

**Comment by fralx** [comment]
I apologize for the long wait. You have done a huge job and it takes me a lot of time to check the compatibility of the changes with the previously created report templates.

**Comment by yanis60** [comment]
Thank you,
I have already tested with old templates and it works perfectly, you need to push this pull in order to add new features ;)

**Comment by yanis60** [comment]
a great new features that are rejected :'(

**Comment by Jihadist** [comment]
@yanis60 i found that this commit broke cmake shared build. Did you try shared build?

**Comment by yanis60** [comment]
@Jihadist not yet

**Pull request merged**
