### PR TITLE
Adding barcode field from the data source

### PR DESCRIPTION
**Pull request by AndrzejWoronko**

### CODE REVIEW

**Comment by fralx** [comment]
Hi @liufeijin !
Maybe I do not clearly understand what you really need, but you can change barcode type to QRCODE in the BarcodeItem and  you will get the QRCode in the limereport

**Comment by liufeijin** [comment]
Hi 
I want to generate the QRcode according with given chart like as below
TIM截图20190620154525
seems LimeReport only support .

**Comment by fralx** [comment]
Ok, I will think about it :) I will see your files and maybe I create a new barcode item.

**Comment by liufeijin** [comment]
oh good news!
Use a new item will be best as the third part lib( attachment above) accepts many attributes for size , error level, logo etc ...

**Comment by liufeijin** [comment]
hi fralx
About this , i used a image item and barcode item to get the above effect 

so no need to create a new item?

**Pull request merged**
