### PR TITLE
to fix the crash issue when we used the designer.

### PR DESCRIPTION
**Pull request by turbin**
```
ObjectPropItem::setPropertyValue(extractAcceptableValue(value.toInt())[0]);
```
the function extractAcceptableValue()  would return a empty container,then call function operator()[] with 0  as a index would cause the crash.

I have setted some protect code to avoid this situation, and this patch was passing my test.

### CODE REVIEW

**Comment by turbin** [comment]
I have completed a new feature to controlling the max number of items in data band.
it was tested and it's performance was perfect.

**Comment by fralx** [comment]
Hi! 
Thanks for your contribution! 
Could you split the changes into two different pull requests? 
The first one for the designer crash issue, the second for the feature.

**Review by fralx — CHANGES_REQUESTED** [review]
Please keep in mind that LimeReport is still compatible with Qt4.  Considering this you shouldn't use QVector.takeFirst() (was introduced in Qt 5). 
Please remove QDebug output and ts files from a commit

**Comment by turbin** [comment]
> Please keep in mind that LimeReport is still compatible with Qt4. Considering this you shouldn't use QVector.takeFirst() (was introduced in Qt 5).
> Please remove QDebug output and ts files from a commit

sorry for my fault. 
This is my first time to contribute the code in github.
I would try to commit my code as your requirement.

**Comment by fralx** [comment]
Hi! You shouldn't delete files from the project :) because if I merge this request it will delete files in my project. To be simple you can create a new fork and make changes to it.

**Pull request closed without merging**
