### PR TITLE
Update Chinese translation for  branch develop

### PR DESCRIPTION
**Pull request by wartime**

### CODE REVIEW

**Comment by fralx** [comment]
Thanks :)

**Comment by fralx** [comment]
Can I ask you time to time update the translation?

**Comment by fralx** [comment]
Hi! Can I ask you to translate the new version 1.5 to Chinese?

**Comment by liufeijin** [comment]
> Hi! Can I ask you to translate the new version 1.5 to Chinese?

Hi fralx
I want to translate the new version 1.5 to Chinese.
But i have not did like this, if you can give some guide is better.

**Comment by wartime** [comment]
@fralx translation for version 1.5 is done on master branch.

**Comment by fralx** [comment]
@wartime 
Thanks :)
@liufeijin 
Hi, it's pretty simple :) You just open limereport_zh.ts from the translation subfolder with qt tool linguist and translate it :)

**Comment by liufeijin** [comment]
> @wartime
> Thanks :)
> @liufeijin
> Hi, it's pretty simple :) You just open limereport_zh.ts from the translation subfolder with qt tool linguist and translate it :)

Hi fralx
i use linguist to open limereport_zh.ts but got the error as below
TIM截图20190706102206

**Comment by fralx** [comment]
@liufeijin HI, it is very strange. For me the linguist working as expected. 
linguist

**Comment by liufeijin** [comment]
I am using QT5.12.2 what is your QT rev.?

**Pull request merged**
